
import tweepy #type: ignore

from typing import Iterable, Optional, Protocol

from protocols import SystemProtocol
from herald import HeraldProtocol
from plugins.data_system import DataSystemEvent

class DataSystemProtocol(SystemProtocol, HeraldProtocol[DataSystemEvent], Protocol):
	"""Provides cached interface with twitter api"""

	def is_processed(self, user_id: int) -> bool: ...
	def tag_processed(self, user_id: int): ...
	def get_id(self, username: str) -> Optional[int]: ...
	def get_user(self, id: int) -> Optional[tweepy.User]: ...
	def get_tweet(self, id: int) -> Optional[tweepy.Tweet]: ...
	def get_recent_tweets(self, user_id: int) -> Iterable[int]: ...
	def get_followers(self, user_id: int) -> Iterable[int]: ...
	def is_tweet_processed(self, tweet_id: int) -> bool: ...
	def tag_tweet_processed(self, tweet_id: int): ...
